name: Build latest from compose-workflow
 
on:
  push:
    branches: [ main ] # This watches the branch called "main"
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD
      # - name: "Say Hello"
      #   env:
      #     First_Name: WORLD
      #   run: echo "HELLO $First_Name"
=======
      - name: "Say Hello"
        env:
          First_Name: WORLD
        run: echo "HELLO $First_Name"
>>>>>>> 49aa53ae4451766824c65ab6f60cd910f4aa4f60
      - name: Build image and push to GitHub Container Registry
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }} 
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 'ghcr.io/sethaj/rails-sharkinfo-k8s/rails-sharkinfo-k8s:${{ github.sha }}, ghcr.io/sethaj/rails-sharkinfo-k8s/rails-sharkinfo-k8s:latest'
          file: Dockerfile.prod